apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: cloud-gw
spec:
  controllerName: "github.com/pixelperfekt-dk/cloud-gateway-controller"
  parametersRef:
    group: v1
    kind: ConfigMap
    name: cloud-gw-gateway-class
    namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-gw-gateway-class
  namespace: default
data:
  tier2GatewayClass: istio
  albTemplate: |
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: {{ .Name }}
      namespace: {{ .Namespace }}
    spec:
      ingressClassName: contour
      rules:
      - http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Name }}-istio
                port:
                  number: 80
