apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: rt1
spec:
  parentRefs:
  - kind: Gateway
    name: foo-gateway-api-istio
  rules:
  - backendRefs:
    - name: http-echo
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /foo
