{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cloud-gateway-controller.fullname" . }}
  labels:
    {{- include "cloud-gateway-controller.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cloud-gateway-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "cloud-gateway-controller.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
