{{- if .Values.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cloud-gateway-controller.fullname" . }}
  labels:
    {{- include "cloud-gateway-controller.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.clusterRole.rules | nindent 2 }}
{{- end}}
