apiVersion: metacontroller.k8s.io/{{.Values.metacontroller.apiVersion}}
kind: CompositeController
metadata:
  name: {{ include "cloud-gateway-controller.fullname" . }}
  labels:
    {{- include "cloud-gateway-controller.labels" . | nindent 4 }}
spec:
  generateSelector: true
  parentResource:
    apiVersion: gateway.networking.k8s.io/v1beta1
    resource: gateways
  childResources:
  - apiVersion: gateway.networking.k8s.io/v1beta1
    resource: gateways
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://{{ include "cloud-gateway-controller.fullname" . }}.{{ .Release.Namespace }}.svc/sync
