name: Build all platforms

on: [ push, pull_request ]

jobs:
  crossbuild:
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        go-version: [ "1.19" ]
        platform: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build containers
      run: make all-container GO_VERSION=${{ matrix.go-version }}

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push containers
      run: make manifest-list
